#!/usr/bin/env python3
"""
Schreibwerkstatt-Aufgaben für die A2-Lektionen.

Skalierung: 10–30 Wörter pro Aufgabe (A2-Niveau).
Aufgaben thematisch gebunden an die jeweilige Lektion.

Wird vom Patcher add-schreibwerkstatt-v2.py automatisch geladen, wenn er
mit --niveau A2 läuft.
"""
from __future__ import annotations

BANNER = ('https://images.pexels.com/photos/733856/pexels-photo-733856.jpeg?auto=compress&cs=tinysrgb&w=800',
          'Notizbuch und Stift, bereit zum Schreiben')

CONFIGS = {
    # =====================================================================
    # R-Dateien (Lesetexte)
    # =====================================================================
    '1014R': {
        'lesson_code': '1014R',
        'lesson_title': 'Die Hochzeit',
        'banner_url': BANNER[0], 'banner_alt': BANNER[1],
        'intro': 'Fünf kleine Schreibaufgaben rund um „Die Hochzeit" und Hochzeitsfeste in deinem Leben.',
        'tasks': [
            {'titel': 'Eine Hochzeit, die du erlebt hast', 'frage': 'Warst du schon mal auf einer Hochzeit? Wessen Hochzeit war es? Schreib zwei oder drei Sätze.',
             'beispiel': 'Letztes Jahr war ich auf der Hochzeit von meiner Cousine. Die Feier war im Sommer und sehr schön.'},
            {'titel': 'Hochzeitsbräuche in deinem Land', 'frage': 'Wie feiert man eine Hochzeit in deinem Land? Schreib zwei Sätze über Essen, Musik oder Kleidung.',
             'beispiel': 'In Spanien feiern wir lange — bis 5 Uhr morgens. Die Gäste tanzen viel und es gibt viel Wein.'},
            {'titel': 'Eine Glückwunschkarte an Petra und Jens', 'frage': 'Schreib eine kurze Karte an das Brautpaar. Drei oder vier Sätze.',
             'beispiel': 'Liebe Petra, lieber Jens! Herzlichen Glückwunsch zur Hochzeit. Wir wünschen euch viele glückliche Jahre zusammen. Eure Maria.'},
            {'titel': 'Eine Frage an Tina', 'frage': 'Tina ist allein auf der Hochzeit, weil sie und Paul sich getrennt haben. Was möchtest du Tina fragen?',
             'beispiel': 'Tina, geht es dir heute besser? Möchtest du nachher mit uns tanzen?'},
            {'titel': 'Mini-Dialog: Auf der Tanzfläche', 'frage': 'Du bist auf der Hochzeit und triffst einen Gast. Schreib einen Mini-Dialog mit zwei Fragen und zwei Antworten.',
             'beispiel': '— Hallo, woher kennst du das Brautpaar? — Ich bin der Bruder von Jens. Und du? — Ich bin eine Freundin von Petra aus der Schule. — Ach, dann müssen wir tanzen!'},
        ]
    },
    '1024R': {
        'lesson_code': '1024R',
        'lesson_title': 'Die neue Sekretärin',
        'banner_url': BANNER[0], 'banner_alt': BANNER[1],
        'intro': 'Fünf kleine Schreibaufgaben rund um Tims Suche nach einer Sekretärin und deine eigene Arbeitswelt.',
        'tasks': [
            {'titel': 'Dein Beruf', 'frage': 'Was machst du beruflich? Wo arbeitest du? Schreib zwei oder drei Sätze.',
             'beispiel': 'Ich arbeite als Lehrerin in einer Sprachschule. Wir unterrichten Spanisch und Englisch. Meine Schule ist in Madrid.'},
            {'titel': 'Eine Bewerbung', 'frage': 'Hast du schon einmal eine Bewerbung geschrieben? Wofür? Schreib zwei Sätze.',
             'beispiel': 'Letztes Jahr habe ich mich um eine neue Stelle beworben. Ich wollte als Sekretärin in einer Anwaltskanzlei arbeiten.'},
            {'titel': 'Was suchst du in einer Stelle?', 'frage': 'Was ist dir bei einer Arbeit wichtig? Drei Sachen — z.B. Gehalt, Kollegen, Ort.',
             'beispiel': 'Mir sind nette Kollegen am wichtigsten. Auch ein gutes Gehalt ist mir wichtig. Und ich möchte nicht zu lange pendeln.'},
            {'titel': 'Eine Frage an Nadia', 'frage': 'Nadia hat die Stelle bei Tim bekommen. Was möchtest du sie fragen?',
             'beispiel': 'Frau Schmidt, warum haben Sie sich bei Herrn Wagner beworben?'},
            {'titel': 'Mini-Dialog: Im Vorstellungsgespräch', 'frage': 'Du bist im Vorstellungsgespräch. Schreib einen kurzen Dialog mit zwei Fragen und zwei Antworten.',
             'beispiel': '— Warum möchten Sie bei uns arbeiten? — Ich finde die Firma sehr interessant. — Was sind Ihre Stärken? — Ich bin pünktlich und arbeite gern im Team.'},
        ]
    },
    '1034R': {
        'lesson_code': '1034R',
        'lesson_title': 'Die neue Wohnung',
        'banner_url': BANNER[0], 'banner_alt': BANNER[1],
        'intro': 'Fünf kleine Schreibaufgaben rund um Louises Wohnungssuche und deine eigene Wohnung.',
        'tasks': [
            {'titel': 'Deine Wohnung', 'frage': 'Wie ist deine Wohnung? Beschreib sie in zwei oder drei Sätzen: Größe, Stockwerk, hell oder dunkel.',
             'beispiel': 'Ich wohne in einer Drei-Zimmer-Wohnung im zweiten Stock. Sie ist hell und hat einen kleinen Balkon. Mir gefällt es hier sehr.'},
            {'titel': 'Deine Traumwohnung', 'frage': 'Wie soll deine Traumwohnung aussehen? Schreib drei Sachen, die wichtig sind.',
             'beispiel': 'Meine Traumwohnung hat einen großen Balkon mit Blick auf einen Park. Sie hat ein Arbeitszimmer und eine moderne Küche.'},
            {'titel': 'Vor- und Nachteile deines Wohnorts', 'frage': 'Was ist gut, was ist schlecht an deinem Wohnort? Schreib einen Vorteil und einen Nachteil.',
             'beispiel': 'Mein Viertel ist sehr ruhig — das ist toll. Aber es gibt nur wenige Restaurants in der Nähe — das ist ein Nachteil.'},
            {'titel': 'Eine Anzeige schreiben', 'frage': 'Stell dir vor, du suchst eine neue Wohnung. Schreib eine kurze Anzeige (3-4 Zeilen).',
             'beispiel': 'Suche helle 2-Zimmer-Wohnung in Berlin-Mitte, mit Balkon, ab 1. Juni. Bis 900 Euro Kaltmiete. Bitte melden bei: maria@email.de'},
            {'titel': 'Mini-Dialog: Beim Makler', 'frage': 'Du sprichst mit einem Makler über eine Wohnung. Schreib zwei Fragen und zwei Antworten.',
             'beispiel': '— Wie groß ist die Wohnung? — Sie hat 65 Quadratmeter. — Was kostet die Kaltmiete? — 850 Euro pro Monat.'},
        ]
    },
    '1044R': {
        'lesson_code': '1044R',
        'lesson_title': 'Das erste Date',
        'banner_url': BANNER[0], 'banner_alt': BANNER[1],
        'intro': 'Fünf kleine Schreibaufgaben rund um Alex\' und Louises erstes Date und deine eigenen Erfahrungen.',
        'tasks': [
            {'titel': 'Dein Lieblingsmuseum', 'frage': 'Welches Museum magst du? Was kann man dort sehen? Schreib zwei Sätze.',
             'beispiel': 'Ich gehe gern ins Prado-Museum in Madrid. Dort kann man berühmte Bilder von Goya und Velázquez sehen.'},
            {'titel': 'Ein Tag mit deiner Liebe', 'frage': 'Wie sieht dein perfekter Tag mit deinem Partner aus? Drei Stationen.',
             'beispiel': 'Morgens gehen wir zusammen in ein Café. Mittags machen wir einen Spaziergang im Park. Abends kochen wir zu Hause.'},
            {'titel': 'Ein Picknick', 'frage': 'Wo machst du gern ein Picknick? Was nimmst du mit? Schreib zwei Sätze.',
             'beispiel': 'Ich mache gern Picknick im Retiro-Park in Madrid. Ich nehme Brot, Käse und eine Flasche Wein mit.'},
            {'titel': 'Eine Frage an Alex', 'frage': 'Alex war beim Date sehr nervös. Was möchtest du ihn fragen?',
             'beispiel': 'Alex, warum warst du am Anfang so nervös? Hat dir Louise schon vorher gefallen?'},
            {'titel': 'Mini-Dialog: Im Restaurant', 'frage': 'Du bist mit deiner Liebe im Restaurant. Schreib zwei Fragen und zwei Antworten.',
             'beispiel': '— Was möchtest du essen? — Vielleicht Pasta. Und du? — Ich nehme Pizza. — Trinken wir Wein dazu? — Ja, gern!'},
        ]
    },
    '1054R': {
        'lesson_code': '1054R',
        'lesson_title': 'Eine neue Sportart',
        'banner_url': BANNER[0], 'banner_alt': BANNER[1],
        'intro': 'Fünf kleine Schreibaufgaben rund um Alex\' Suche nach einer neuen Sportart und deinen eigenen Sport.',
        'tasks': [
            {'titel': 'Dein Sport', 'frage': 'Welchen Sport machst du? Wie oft? Schreib zwei oder drei Sätze.',
             'beispiel': 'Ich gehe zweimal pro Woche schwimmen. Schwimmen entspannt mich nach der Arbeit. Manchmal mache ich auch Yoga.'},
            {'titel': 'Im Stadion oder zu Hause?', 'frage': 'Schaust du Sport lieber im Stadion oder im Fernsehen? Warum? Schreib zwei Sätze.',
             'beispiel': 'Ich schaue Fußball lieber im Stadion. Die Atmosphäre ist viel besser als zu Hause auf dem Sofa.'},
            {'titel': 'Drei Vorteile von Sport', 'frage': 'Warum ist Sport gut für dich? Schreib drei Vorteile.',
             'beispiel': 'Sport macht mich gesund. Sport macht mir gute Laune. Beim Sport lerne ich neue Leute kennen.'},
            {'titel': 'Eine Frage an Alex', 'frage': 'Alex möchte eine neue Sportart anfangen. Was möchtest du ihm vorschlagen oder fragen?',
             'beispiel': 'Alex, warum probierst du nicht Tischtennis? Das ist auch ein Teamsport und macht großen Spaß.'},
            {'titel': 'Mini-Dialog: Im Schwimmbad', 'frage': 'Du bist mit einem Freund im Schwimmbad. Schreib zwei Fragen und zwei Antworten.',
             'beispiel': '— Wie oft kommst du her? — Dreimal pro Woche. Und du? — Ich komme nur am Wochenende. — Schwimmen wir 20 Bahnen? — Okay, los geht\'s!'},
        ]
    },
    '1064R': {
        'lesson_code': '1064R',
        'lesson_title': 'Pläne für die Zukunft',
        'banner_url': BANNER[0], 'banner_alt': BANNER[1],
        'intro': 'Fünf kleine Schreibaufgaben rund um Hermines Zukunftspläne und deine eigenen Pläne.',
        'tasks': [
            {'titel': 'Deine Sommerferien', 'frage': 'Was machst du in den nächsten Sommerferien? Wohin fährst du? Schreib zwei Sätze.',
             'beispiel': 'In den Sommerferien fliege ich mit meiner Familie nach Italien. Wir wollen zwei Wochen am Meer bleiben.'},
            {'titel': 'Ein Praktikum', 'frage': 'Hast du schon ein Praktikum gemacht? Wo? Wenn nicht: wo möchtest du eines machen?',
             'beispiel': 'Ich habe ein Praktikum in einer Bank gemacht. Es war drei Monate lang und sehr interessant.'},
            {'titel': 'Dein Traumberuf', 'frage': 'Was möchtest du beruflich werden oder bleiben? Warum? Schreib zwei Sätze.',
             'beispiel': 'Ich möchte Architektin werden. Mir gefällt es, Häuser zu zeichnen und kreative Lösungen zu finden.'},
            {'titel': 'Eine Frage an Hermine', 'frage': 'Hermine ist unsicher zwischen Krankenschwester und Ärztin. Was möchtest du sie fragen?',
             'beispiel': 'Hermine, was findest du am Beruf der Krankenschwester am schönsten?'},
            {'titel': 'Mini-Dialog: Über die Zukunft', 'frage': 'Du sprichst mit einem Freund über die Zukunft. Schreib zwei Fragen und zwei Antworten.',
             'beispiel': '— Was machst du nach der Schule? — Ich mache vielleicht eine Ausbildung. — In welchem Bereich? — In einem Krankenhaus. Das interessiert mich.'},
        ]
    },
    '2014R': {
        'lesson_code': '2014R',
        'lesson_title': 'Ein neuer Ernährungsplan',
        'banner_url': BANNER[0], 'banner_alt': BANNER[1],
        'intro': 'Fünf kleine Schreibaufgaben rund um Alex\' Ernährungsplan und deine eigenen Essgewohnheiten.',
        'tasks': [
            {'titel': 'Deine Ernährung', 'frage': 'Wie ernährst du dich normalerweise? Eher gesund oder eher ungesund? Schreib zwei Sätze.',
             'beispiel': 'Ich esse meistens gesund — viel Gemüse und Obst. Aber am Wochenende esse ich gern eine Pizza oder einen Burger.'},
            {'titel': 'Dein Lieblingsessen', 'frage': 'Was ist dein Lieblingsessen? Was sind die Zutaten? Schreib zwei oder drei Sätze.',
             'beispiel': 'Mein Lieblingsessen ist Paella. Sie hat Reis, Hähnchen, Garnelen und viel Gemüse. Meine Mutter macht die beste Paella.'},
            {'titel': 'Drei Lebensmittel, die du kaufst', 'frage': 'Was kaufst du jede Woche im Supermarkt? Nenne drei Sachen mit Mengen.',
             'beispiel': 'Ich kaufe jede Woche einen Liter Milch, ein Kilo Tomaten und ein Brot. Manchmal auch ein Stück Käse.'},
            {'titel': 'Eine Frage an Louise', 'frage': 'Louise ernährt sich gesund. Was möchtest du sie fragen?',
             'beispiel': 'Louise, hast du Tipps für ein schnelles und gesundes Frühstück?'},
            {'titel': 'Mini-Dialog: Im Restaurant', 'frage': 'Du bestellst etwas Gesundes im Restaurant. Schreib zwei Fragen und zwei Antworten.',
             'beispiel': '— Haben Sie etwas Vegetarisches? — Ja, einen Salat oder eine Gemüsepfanne. — Was empfehlen Sie? — Die Gemüsepfanne ist heute sehr lecker.'},
        ]
    },
    '2024R': {
        'lesson_code': '2024R',
        'lesson_title': 'Mein bester Urlaub',
        'banner_url': BANNER[0], 'banner_alt': BANNER[1],
        'intro': 'Fünf kleine Schreibaufgaben rund um Alex\' und Nils\' New-York-Trip und deinen besten Urlaub.',
        'tasks': [
            {'titel': 'Dein bester Urlaub', 'frage': 'Wo warst du in deinem schönsten Urlaub? Was war besonders? Schreib zwei oder drei Sätze.',
             'beispiel': 'Mein schönster Urlaub war in Thailand. Wir waren zwei Wochen am Strand und haben sehr gutes Essen gegessen.'},
            {'titel': 'Drei Sehenswürdigkeiten', 'frage': 'Welche drei Sehenswürdigkeiten möchtest du gern sehen? Wo sind sie?',
             'beispiel': 'Ich möchte den Eiffelturm in Paris, das Kolosseum in Rom und die Pyramiden in Ägypten sehen.'},
            {'titel': 'Ein Reise-Missgeschick', 'frage': 'Hattest du schon einmal Probleme im Urlaub? Schreib zwei Sätze über ein kleines Missgeschick.',
             'beispiel': 'Letztes Jahr habe ich meinen Koffer im Flugzeug verloren. Ich musste zwei Tage ohne Kleidung warten.'},
            {'titel': 'Eine Frage an Alex und Nils', 'frage': 'Alex und Nils hätten fast den Flug verpasst. Was möchtest du sie fragen?',
             'beispiel': 'Was war für euch in New York am eindrucksvollsten — die Freiheitsstatue oder das Empire State Building?'},
            {'titel': 'Mini-Dialog: Am Flughafen', 'frage': 'Du bist am Flughafen und hast etwas vergessen. Schreib zwei Fragen und zwei Antworten.',
             'beispiel': '— Entschuldigung, wo ist der Schalter von Lufthansa? — Dort drüben, am Schalter B12. — Wann muss ich einchecken? — Ihr Flug geht in zwei Stunden.'},
        ]
    },
    '2034R': {
        'lesson_code': '2034R',
        'lesson_title': 'Eine Woche voller Missgeschicke',
        'banner_url': BANNER[0], 'banner_alt': BANNER[1],
        'intro': 'Fünf kleine Schreibaufgaben rund um Stefans Pechwoche und Missgeschicke in deinem Leben.',
        'tasks': [
            {'titel': 'Ein Missgeschick aus deinem Leben', 'frage': 'Was ist dir schon einmal Peinliches passiert? Schreib zwei oder drei Sätze.',
             'beispiel': 'Letzte Woche bin ich vor allen Kollegen gestolpert. Mein Kaffee ist auf den Boden gefallen. Alle haben gelacht.'},
            {'titel': 'Beim Friseur', 'frage': 'Warst du schon einmal bei einem schlechten Friseur? Was ist passiert?',
             'beispiel': 'Vor einem Jahr hat mir der Friseur die Haare zu kurz geschnitten. Ich war zwei Monate lang sehr unglücklich.'},
            {'titel': 'Drei Probleme — drei Lösungen', 'frage': 'Stefan hatte viele Probleme. Schreib drei Probleme aus deinem Leben mit Lösung.',
             'beispiel': 'Mein Auto ging kaputt — ich nahm den Bus. Die Bank schloss zu früh — ich kam morgen wieder. Mein Drucker streikte — ich bat einen Kollegen.'},
            {'titel': 'Eine Frage an Stefan', 'frage': 'Stefan hat trotz Pechwoche die Stelle bekommen. Was möchtest du ihn fragen?',
             'beispiel': 'Stefan, warum konntest du in dem zu großen Anzug ruhig bleiben? Hattest du keine Angst?'},
            {'titel': 'Mini-Dialog: In der Reinigung', 'frage': 'Du bringst etwas zur Reinigung. Schreib zwei Fragen und zwei Antworten.',
             'beispiel': '— Wann ist mein Anzug fertig? — Übermorgen, gegen 16 Uhr. — Was kostet die Reinigung? — 12 Euro für den Anzug. — Danke, ich hole ihn dann ab.'},
        ]
    },
    '2044R': {
        'lesson_code': '2044R',
        'lesson_title': 'Hermines Geschichte',
        'banner_url': BANNER[0], 'banner_alt': BANNER[1],
        'intro': 'Fünf kleine Schreibaufgaben rund um Hermines Schnuppertag in Berlin und deine Studien- oder Berufswahl.',
        'tasks': [
            {'titel': 'Deine Schule oder Uni', 'frage': 'Erzähl von deiner Schule oder Uni. Wo war/ist sie? Was hast du gelernt? Schreib zwei oder drei Sätze.',
             'beispiel': 'Ich war auf dem Gymnasium in Madrid. Meine Lieblingsfächer waren Mathe und Englisch. Jetzt studiere ich Wirtschaft.'},
            {'titel': 'Ein Schnuppertag', 'frage': 'Möchtest du einen Schnuppertag an einer Uni machen? Wo und in welchem Fach? Zwei Sätze.',
             'beispiel': 'Ich möchte einen Schnuppertag an der Universität in Hamburg machen. Mich interessiert das Fach Psychologie sehr.'},
            {'titel': 'Studium oder Ausbildung?', 'frage': 'Was findest du besser — Studium oder Ausbildung? Warum? Schreib zwei Sätze.',
             'beispiel': 'Ich finde eine Ausbildung gut, weil man dabei Geld verdient. Ein Studium ist auch interessant, aber dauert sehr lange.'},
            {'titel': 'Eine Frage an Hermine', 'frage': 'Hermine ist unsicher. Was möchtest du sie fragen oder welchen Rat möchtest du ihr geben?',
             'beispiel': 'Hermine, hast du schon mit anderen Studenten gesprochen? Sie können dir Tipps geben.'},
            {'titel': 'Mini-Dialog: Im Studienberatungsbüro', 'frage': 'Du sprichst mit einer Beraterin. Schreib zwei Fragen und zwei Antworten.',
             'beispiel': '— Welcher Studiengang passt zu mir? — Was sind deine Stärken? — Ich rede gern und arbeite mit Menschen. — Vielleicht passt Lehramt oder Soziale Arbeit gut zu dir.'},
        ]
    },
    '2054R': {
        'lesson_code': '2054R',
        'lesson_title': 'Soziale Netzwerke',
        'banner_url': BANNER[0], 'banner_alt': BANNER[1],
        'intro': 'Fünf kleine Schreibaufgaben rund um soziale Netzwerke und dein eigenes Online-Leben.',
        'tasks': [
            {'titel': 'Welche Netzwerke nutzt du?', 'frage': 'Welche sozialen Netzwerke nutzt du? Wie oft pro Tag? Schreib zwei Sätze.',
             'beispiel': 'Ich nutze WhatsApp jeden Tag — sicher zwei Stunden. Instagram schaue ich nur abends, vielleicht 30 Minuten.'},
            {'titel': 'Was postest du gern?', 'frage': 'Postest du Fotos oder Videos? Welche Themen? Schreib zwei oder drei Sätze.',
             'beispiel': 'Ich poste gern Fotos von meinem Hund. Manchmal auch Bilder vom Essen oder vom Urlaub. Texte schreibe ich selten.'},
            {'titel': 'Drei Vor- und Nachteile', 'frage': 'Schreib zwei Vorteile und einen Nachteil sozialer Netzwerke.',
             'beispiel': 'Vorteile: ich bleibe mit Freunden in Kontakt und finde schnelle Infos. Nachteil: ich verbringe zu viel Zeit am Handy.'},
            {'titel': 'Influencer werden?', 'frage': 'Möchtest du Influencer oder Content Creator werden? Warum (nicht)?',
             'beispiel': 'Nein, ich möchte kein Influencer werden. Ich möchte meine Privatsphäre haben und nicht ständig vor der Kamera sein.'},
            {'titel': 'Mini-Dialog: Über Social Media', 'frage': 'Du sprichst mit einem Freund über soziale Netzwerke. Schreib zwei Fragen und zwei Antworten.',
             'beispiel': '— Bist du auch auf TikTok? — Nein, mir reicht Instagram. — Warum? — Ich habe sonst zu wenig Zeit für andere Sachen.'},
        ]
    },
    '2064R': {
        'lesson_code': '2064R',
        'lesson_title': 'In der Natur',
        'banner_url': BANNER[0], 'banner_alt': BANNER[1],
        'intro': 'Fünf kleine Schreibaufgaben rund um Camping, Natur und deine Outdoor-Erlebnisse.',
        'tasks': [
            {'titel': 'Camping oder Hotel?', 'frage': 'Was findest du besser — Campen oder Hotelurlaub? Warum? Schreib zwei Sätze.',
             'beispiel': 'Ich finde Camping gut, weil man die Natur erlebt. Aber im Hotel hat man eine warme Dusche und ein bequemes Bett.'},
            {'titel': 'Ein Wochenende im Wald', 'frage': 'Was nimmst du mit, wenn du ein Wochenende im Wald verbringst? Nenne mindestens vier Sachen.',
             'beispiel': 'Ich nehme einen Schlafsack, ein Zelt, Wanderschuhe, eine Taschenlampe und Proviant für drei Tage mit.'},
            {'titel': 'Eine Wettersituation', 'frage': 'Hast du schon einmal schlechtes Wetter im Urlaub erlebt? Was hast du gemacht?',
             'beispiel': 'In Schottland hat es eine ganze Woche geregnet. Wir sind viel ins Café gegangen und haben Bücher gelesen.'},
            {'titel': 'Eine Frage an Louise', 'frage': 'Louise hat Angst vor Bären. Was möchtest du sie fragen?',
             'beispiel': 'Louise, würdest du noch einmal im Wald campen? Oder nur im Hotel übernachten?'},
            {'titel': 'Mini-Dialog: An der Hotelrezeption', 'frage': 'Du kommst aus dem Regen ins Hotel. Schreib zwei Fragen und zwei Antworten.',
             'beispiel': '— Haben Sie noch ein Zimmer frei? — Ja, ein Doppelzimmer für 95 Euro. — Hat das Zimmer eine Dusche? — Ja, und eine Badewanne.'},
        ]
    },
    # =====================================================================
    # X-Dateien (Textarbeit / Grammatik & Wortschatz)
    # =====================================================================
    '1012X': {
        'lesson_code': '1012X',
        'lesson_title': 'Romantik und Date',
        'banner_url': BANNER[0], 'banner_alt': BANNER[1],
        'intro': 'Fünf kleine Schreibaufgaben rund um Romantik, Dates und Geschenke.',
        'tasks': [
            {'titel': 'Dein bestes Date', 'frage': 'Was war dein schönstes Date? Wo wart ihr? Was habt ihr gemacht? Schreib zwei oder drei Sätze.',
             'beispiel': 'Mein schönstes Date war ein Picknick im Park. Wir haben Erdbeeren und Champagner getrunken. Es war sehr romantisch.'},
            {'titel': 'Was-für-Fragen', 'frage': 'Stell drei Was-für-Fragen an einen Freund über sein perfektes Date.',
             'beispiel': 'Was für Blumen magst du? Was für ein Restaurant findest du schön? Was für eine Musik hörst du gern?'},
            {'titel': 'Ein Geschenk zum Valentinstag', 'frage': 'Was schenkst du zum Valentinstag? Schreib zwei Sätze.',
             'beispiel': 'Ich schenke meinem Freund eine Schachtel Pralinen und eine schöne Karte. Er liebt dunkle Schokolade.'},
            {'titel': 'Eine kurze Liebeskarte', 'frage': 'Schreib eine kurze Karte an deine Liebe (3-4 Sätze).',
             'beispiel': 'Lieber Tom! Du bist die beste Person in meinem Leben. Ich liebe dein Lachen. Alles Gute zum Valentinstag! Deine Maria.'},
            {'titel': 'Mini-Dialog: Ein Date verabreden', 'frage': 'Du verabredest dich mit jemandem. Schreib zwei Fragen und zwei Antworten.',
             'beispiel': '— Hast du am Samstag Zeit? — Ja, gern. Was machen wir? — Vielleicht ein Picknick im Park? — Tolle Idee, ich freue mich!'},
        ]
    },
    '1016X': {
        'lesson_code': '1016X',
        'lesson_title': 'Höflichkeit',
        'banner_url': BANNER[0], 'banner_alt': BANNER[1],
        'intro': 'Fünf kleine Schreibaufgaben rund um Höflichkeit, „du" oder „Sie" und Bitten.',
        'tasks': [
            {'titel': 'Duzen oder siezen?', 'frage': 'Wen siezt du? Wen duzt du? Schreib zwei Sätze.',
             'beispiel': 'Meine Nachbarn sieze ich, weil sie viel älter sind. Meine Kollegen duze ich, weil wir uns gut kennen.'},
            {'titel': 'Drei höfliche Bitten', 'frage': 'Schreib drei Bitten mit „Könnten Sie…?" oder „Könntest du…?".',
             'beispiel': 'Könnten Sie mir bitte das Salz reichen? Könntest du das Fenster aufmachen? Könnten Sie noch einen Kaffee bringen?'},
            {'titel': 'Eine Entschuldigung', 'frage': 'Du kommst zu spät zur Arbeit. Schreib zwei oder drei höfliche Sätze an deinen Chef.',
             'beispiel': 'Sehr geehrter Herr Wagner, ich entschuldige mich für meine Verspätung. Der Bus ist heute leider nicht gekommen.'},
            {'titel': 'Höflich oder unhöflich?', 'frage': 'Wer war zu dir besonders höflich oder unhöflich? Schreib zwei Sätze.',
             'beispiel': 'Gestern hat mir ein Mann im Bus seinen Platz angeboten. Das war sehr höflich. Aber an der Kasse hat eine Frau geschrien — das war unhöflich.'},
            {'titel': 'Mini-Dialog: Im Restaurant', 'frage': 'Schreib einen höflichen Mini-Dialog mit Kellner: zwei Fragen und zwei Antworten.',
             'beispiel': '— Entschuldigung, könnten Sie mir die Karte bringen? — Natürlich, gerne. — Könnte ich auch ein Glas Wasser haben? — Sicher, kommt sofort.'},
        ]
    },
    '1022X': {
        'lesson_code': '1022X',
        'lesson_title': 'Bewerbungen',
        'banner_url': BANNER[0], 'banner_alt': BANNER[1],
        'intro': 'Fünf kleine Schreibaufgaben rund um Bewerbungen, Stellen und Lebenslauf.',
        'tasks': [
            {'titel': 'Deine Berufserfahrung', 'frage': 'Was hast du bisher beruflich gemacht? Schreib zwei oder drei Sätze über Stellen oder Praktika.',
             'beispiel': 'Ich habe drei Jahre als Verkäuferin gearbeitet. Danach habe ich ein Praktikum in einer Bank gemacht. Jetzt bin ich Sekretärin.'},
            {'titel': 'Eine Stellenanzeige', 'frage': 'Stell dir vor, du suchst eine Stelle. Schreib eine kurze Stellenanzeige (3-4 Zeilen).',
             'beispiel': 'Suche Job als Sekretärin in München, Vollzeit, ab 1. September. Drei Jahre Erfahrung in einer Kanzlei. Sehr gute Computerkenntnisse.'},
            {'titel': 'Drei Stärken', 'frage': 'Was sind deine drei wichtigsten Stärken im Beruf? Schreib einen Satz pro Stärke.',
             'beispiel': 'Ich bin sehr pünktlich. Ich arbeite gut im Team. Ich kenne mich mit Computern gut aus.'},
            {'titel': 'Anschreiben — erster Satz', 'frage': 'Schreib den ersten Satz eines Bewerbungsschreibens.',
             'beispiel': 'Sehr geehrte Frau Müller, mit großem Interesse habe ich Ihre Stellenanzeige gelesen und möchte mich um die Stelle als Sekretärin bewerben.'},
            {'titel': 'Mini-Dialog: Im Vorstellungsgespräch', 'frage': 'Schreib zwei Fragen und zwei Antworten aus einem Vorstellungsgespräch.',
             'beispiel': '— Warum möchten Sie bei uns arbeiten? — Ihre Firma macht sehr interessante Projekte. — Wann können Sie anfangen? — Ab dem ersten Mai.'},
        ]
    },
    '1026X': {
        'lesson_code': '1026X',
        'lesson_title': 'Am Telefon',
        'banner_url': BANNER[0], 'banner_alt': BANNER[1],
        'intro': 'Fünf kleine Schreibaufgaben rund um Telefongespräche und Anrufe.',
        'tasks': [
            {'titel': 'Ein Anruf bei der Arztpraxis', 'frage': 'Du rufst beim Arzt an, um einen Termin zu vereinbaren. Schreib drei Sätze.',
             'beispiel': 'Guten Tag, hier ist Maria Lopez. Ich hätte gern einen Termin bei Frau Doktor Müller. Ist es möglich, am Donnerstag zu kommen?'},
            {'titel': 'Eine Nachricht hinterlassen', 'frage': 'Du erreichst niemanden. Was sagst du auf den Anrufbeantworter? Schreib zwei oder drei Sätze.',
             'beispiel': 'Hallo Tom, hier ist Maria. Ich rufe wegen unserer Verabredung am Samstag an. Ruf mich bitte zurück, danke!'},
            {'titel': 'Höflich am Telefon', 'frage': 'Schreib drei höfliche Telefon-Sätze, z.B. zur Begrüßung oder Nachfrage.',
             'beispiel': 'Guten Tag, könnte ich bitte Herrn Wagner sprechen? Entschuldigung, könnten Sie das wiederholen? Vielen Dank für Ihre Hilfe.'},
            {'titel': 'Wenn der Empfang schlecht ist', 'frage': 'Was sagst du, wenn die Verbindung schlecht ist? Schreib zwei Sätze.',
             'beispiel': 'Entschuldigung, ich kann Sie nicht gut hören. Kann ich Sie zurückrufen?'},
            {'titel': 'Mini-Dialog: Falsch verbunden', 'frage': 'Du bist falsch verbunden. Schreib einen kurzen Dialog mit zwei Fragen und zwei Antworten.',
             'beispiel': '— Hallo, ist da die Firma Schmidt? — Nein, hier ist Privat. — Oh, Entschuldigung, falsch verbunden. — Kein Problem, auf Wiederhören.'},
        ]
    },
    '1032X': {
        'lesson_code': '1032X',
        'lesson_title': 'Wo und Wohin',
        'banner_url': BANNER[0], 'banner_alt': BANNER[1],
        'intro': 'Fünf kleine Schreibaufgaben rund um Wechselpräpositionen und Wegbeschreibungen.',
        'tasks': [
            {'titel': 'Drei Wo-Sätze', 'frage': 'Schreib drei Sätze über Dinge in deinem Zimmer mit Wechselpräpositionen (Dativ).',
             'beispiel': 'Mein Buch liegt auf dem Tisch. Die Lampe steht neben dem Bett. Das Bild hängt an der Wand.'},
            {'titel': 'Drei Wohin-Sätze', 'frage': 'Schreib drei Sätze, wohin du etwas legst oder stellst (Akkusativ).',
             'beispiel': 'Ich lege das Buch auf den Tisch. Ich stelle die Lampe neben das Bett. Ich hänge das Bild an die Wand.'},
            {'titel': 'Wegbeschreibung zum Bahnhof', 'frage': 'Erkläre einem Touristen den Weg zum Bahnhof. Schreib drei Sätze mit „geradeaus", „links" oder „rechts".',
             'beispiel': 'Gehen Sie zuerst geradeaus. An der Ampel biegen Sie links ab. Der Bahnhof ist am Ende der Straße.'},
            {'titel': 'Wo wohnst du?', 'frage': 'Beschreib deine Nachbarschaft mit drei Präpositionen.',
             'beispiel': 'Ich wohne in der Hauptstraße. Gegenüber von meinem Haus ist eine Bäckerei. Hinter dem Haus liegt ein Park.'},
            {'titel': 'Mini-Dialog: Nach dem Weg fragen', 'frage': 'Frag nach dem Weg zur Apotheke und antworte.',
             'beispiel': '— Entschuldigung, wo ist die Apotheke? — Gehen Sie geradeaus, dann rechts. — Ist sie weit? — Nein, nur zwei Minuten zu Fuß.'},
        ]
    },
    '1036X': {
        'lesson_code': '1036X',
        'lesson_title': 'Temporale Präpositionen',
        'banner_url': BANNER[0], 'banner_alt': BANNER[1],
        'intro': 'Fünf kleine Schreibaufgaben mit temporalen Präpositionen (seit, vor, ab, bis, nach).',
        'tasks': [
            {'titel': 'Seit wann?', 'frage': 'Schreib zwei Sätze mit „seit" über dein Leben (Wohnort, Beruf, Hobby).',
             'beispiel': 'Ich wohne seit fünf Jahren in Madrid. Ich arbeite seit zwei Monaten in dieser Firma.'},
            {'titel': 'Vor wann?', 'frage': 'Schreib zwei Sätze mit „vor" über dein Leben (z.B. Umzug, Reise).',
             'beispiel': 'Vor drei Jahren bin ich nach Berlin gezogen. Vor sechs Monaten war ich in Italien im Urlaub.'},
            {'titel': 'Ab wann?', 'frage': 'Schreib zwei Sätze mit „ab" über deine Pläne.',
             'beispiel': 'Ab nächstem Monat lerne ich Italienisch. Ab Januar arbeite ich nur noch vier Tage pro Woche.'},
            {'titel': 'Bis wann und nach was?', 'frage': 'Schreib zwei Sätze mit „bis" oder „nach" über deinen Tag.',
             'beispiel': 'Ich arbeite bis 18 Uhr. Nach der Arbeit gehe ich oft ins Schwimmbad oder in den Park.'},
            {'titel': 'Mini-Dialog: Über Zeit reden', 'frage': 'Sprecht über eure Pläne. Schreib zwei Fragen und zwei Antworten mit Zeit-Präpositionen.',
             'beispiel': '— Seit wann lernst du Deutsch? — Seit zwei Jahren. Und du? — Erst seit sechs Monaten. — Ab Januar mache ich einen Intensivkurs.'},
        ]
    },
    '1042X': {
        'lesson_code': '1042X',
        'lesson_title': 'Die Meinung sagen',
        'banner_url': BANNER[0], 'banner_alt': BANNER[1],
        'intro': 'Fünf kleine Schreibaufgaben rund um Meinungen mit „dass" und Redemitteln.',
        'tasks': [
            {'titel': 'Deine Meinung über deine Stadt', 'frage': 'Was findest du an deiner Stadt gut? Schreib einen Satz mit „Ich finde, dass…".',
             'beispiel': 'Ich finde, dass Madrid eine sehr schöne Stadt ist. Es gibt viele Parks und das Wetter ist meistens gut.'},
            {'titel': 'Eine Idee bewerten', 'frage': 'Reagiere auf folgenden Vorschlag: „Wir machen morgen ein Picknick." Schreib zwei Sätze.',
             'beispiel': 'Ich finde, dass das eine super Idee ist. Aber ich denke, dass das Wetter morgen schlecht wird.'},
            {'titel': 'Pro und contra', 'frage': 'Schreib einen Satz mit „Ich bin dafür, dass…" und einen mit „Ich bin dagegen, dass…".',
             'beispiel': 'Ich bin dafür, dass Sport in der Schule wichtig ist. Ich bin dagegen, dass Kinder zu viel am Handy sind.'},
            {'titel': 'Was glaubst du?', 'frage': 'Schreib zwei Sätze mit „Ich glaube, dass…" über die Zukunft.',
             'beispiel': 'Ich glaube, dass die Welt in 20 Jahren digitaler wird. Ich glaube, dass wir mehr im Home-Office arbeiten werden.'},
            {'titel': 'Mini-Dialog: Eine Diskussion', 'frage': 'Diskutiere mit einem Freund über etwas. Schreib zwei Fragen und zwei Antworten mit Redemitteln.',
             'beispiel': '— Was denkst du über das neue Restaurant? — Ich finde, dass es sehr gut ist. — Wirklich? — Ja, meiner Meinung nach ist das Essen super.'},
        ]
    },
    '1046X': {
        'lesson_code': '1046X',
        'lesson_title': 'Temporale Adverbien',
        'banner_url': BANNER[0], 'banner_alt': BANNER[1],
        'intro': 'Fünf kleine Schreibaufgaben mit temporalen Adverbien (morgens, abends, zuerst, dann).',
        'tasks': [
            {'titel': 'Dein Tagesablauf', 'frage': 'Schreib drei Sätze über deinen Tag mit „morgens", „mittags" und „abends".',
             'beispiel': 'Morgens trinke ich Kaffee und lese die Zeitung. Mittags esse ich mit meinen Kollegen. Abends gehe ich oft spazieren.'},
            {'titel': 'Dein Morgen Schritt für Schritt', 'frage': 'Beschreib deinen Morgen mit „zuerst", „dann" und „danach". Drei Sätze.',
             'beispiel': 'Zuerst stehe ich um sieben Uhr auf. Dann gehe ich duschen und ziehe mich an. Danach frühstücke ich in der Küche.'},
            {'titel': 'Früher und heute', 'frage': 'Was war früher anders als jetzt? Schreib zwei Sätze mit „früher" und „heute".',
             'beispiel': 'Früher habe ich viel Fleisch gegessen. Heute esse ich meistens Gemüse und Salat.'},
            {'titel': 'Pläne für später', 'frage': 'Was machst du später am Tag? Schreib zwei Sätze mit „später" und „dann".',
             'beispiel': 'Später muss ich noch einkaufen. Dann koche ich Abendessen für meine Familie.'},
            {'titel': 'Mini-Dialog: Wochenplanung', 'frage': 'Sprecht über euer Wochenende. Schreib zwei Fragen und zwei Antworten mit Adverbien.',
             'beispiel': '— Was machst du heute Abend? — Zuerst gehe ich joggen, danach koche ich. — Und morgens? — Morgens schlafe ich lange aus.'},
        ]
    },
    '1052X': {
        'lesson_code': '1052X',
        'lesson_title': 'Wortbildung — Suffixe',
        'banner_url': BANNER[0], 'banner_alt': BANNER[1],
        'intro': 'Fünf kleine Schreibaufgaben rund um Suffixe (-in, -er, -ung, -heit, -lich).',
        'tasks': [
            {'titel': 'Berufe mit -in und -er', 'frage': 'Schreib drei Sätze über Personen mit dem Suffix „-in" oder „-er".',
             'beispiel': 'Mein Bruder ist Lehrer. Meine Schwester ist Ärztin. Mein Onkel ist Bäcker.'},
            {'titel': 'Eigenschaften mit -heit/-keit', 'frage': 'Schreib drei Sätze mit Nomen, die mit „-heit" oder „-keit" enden.',
             'beispiel': 'Schönheit ist nicht alles. Ich schätze Ehrlichkeit sehr. Höflichkeit kostet nichts.'},
            {'titel': 'Adjektive mit -lich oder -isch', 'frage': 'Schreib drei Sätze mit Adjektiven auf „-lich" oder „-isch".',
             'beispiel': 'Mein Bruder ist sehr sportlich. Wir essen täglich Brot. Das war ein typisch deutsches Frühstück.'},
            {'titel': 'Mit -bar oder -los', 'frage': 'Schreib zwei Sätze mit Adjektiven auf „-bar" oder „-los".',
             'beispiel': 'Diese Pilze sind essbar, aber jene nicht. Mein Bruder ist seit drei Monaten arbeitslos.'},
            {'titel': 'Mini-Dialog: Eigenschaften', 'frage': 'Beschreib einen Freund mit drei Adjektiven mit Suffix.',
             'beispiel': '— Wie ist deine beste Freundin? — Sie ist sehr ehrlich und hilfsbereit. — Was macht sie? — Sie ist Lehrerin und sehr sportlich.'},
        ]
    },
    '1056X': {
        'lesson_code': '1056X',
        'lesson_title': 'Das Verb lassen',
        'banner_url': BANNER[0], 'banner_alt': BANNER[1],
        'intro': 'Fünf kleine Schreibaufgaben rund um das Verb „lassen" und seine Bedeutungen.',
        'tasks': [
            {'titel': 'Was lässt du machen?', 'frage': 'Was lässt du andere für dich machen? Schreib drei Sätze mit „lassen".',
             'beispiel': 'Ich lasse mir die Haare beim Friseur schneiden. Ich lasse mein Auto in der Werkstatt reparieren. Ich lasse die Wohnung putzen.'},
            {'titel': 'Erlaubnis und Verbot', 'frage': 'Schreib einen Satz mit „lassen" als Erlaubnis und einen als Verbot.',
             'beispiel': 'Meine Mutter lässt mich heute fernsehen. Aber sie lässt mich nicht spät ausgehen.'},
            {'titel': 'Vorschlag mit „lass uns"', 'frage': 'Mach drei Vorschläge mit „Lass uns…!".',
             'beispiel': 'Lass uns einen Kaffee trinken! Lass uns ins Kino gehen! Lass uns am Wochenende wandern!'},
            {'titel': 'Lassen im Perfekt', 'frage': 'Schreib zwei Sätze im Perfekt mit „haben + Infinitiv + lassen".',
             'beispiel': 'Letzte Woche habe ich mein Auto reparieren lassen. Gestern habe ich mir die Haare schneiden lassen.'},
            {'titel': 'Mini-Dialog: Beim Friseur', 'frage': 'Du gehst zum Friseur. Schreib zwei Fragen und zwei Antworten.',
             'beispiel': '— Wie möchten Sie es haben? — Ich lasse mir die Haare kurz schneiden. — Auch waschen? — Ja, bitte. Und lass mir auch die Spitzen schneiden.'},
        ]
    },
    '1062X': {
        'lesson_code': '1062X',
        'lesson_title': 'Sätze mit wenn, dann',
        'banner_url': BANNER[0], 'banner_alt': BANNER[1],
        'intro': 'Fünf kleine Schreibaufgaben mit „wenn-dann"-Sätzen über Pläne und Bedingungen.',
        'tasks': [
            {'titel': 'Was machst du, wenn…?', 'frage': 'Schreib drei Sätze mit „Wenn …, dann …" über Alltagssituationen.',
             'beispiel': 'Wenn ich Hunger habe, dann mache ich mir ein Brot. Wenn das Wetter schlecht ist, dann bleibe ich zu Hause. Wenn ich Zeit habe, dann lese ich.'},
            {'titel': 'Deine Lebensziele', 'frage': 'Schreib zwei Sätze über deine Ziele mit „wenn".',
             'beispiel': 'Wenn ich mehr Geld verdiene, dann kaufe ich mir ein neues Auto. Wenn ich Rente bekomme, dann reise ich um die Welt.'},
            {'titel': 'Bedingungen für Glück', 'frage': 'Was macht dich glücklich? Schreib zwei Sätze mit „wenn".',
             'beispiel': 'Wenn die Sonne scheint, dann bin ich glücklich. Wenn meine Familie gesund ist, dann habe ich keine Sorgen.'},
            {'titel': 'Plan B', 'frage': 'Schreib zwei Sätze mit „Wenn das nicht klappt, dann …".',
             'beispiel': 'Wenn ich den Job nicht bekomme, dann bewerbe ich mich woanders. Wenn das Wetter morgen schlecht ist, dann bleiben wir zu Hause.'},
            {'titel': 'Mini-Dialog: Pläne machen', 'frage': 'Sprich mit einem Freund über Pläne. Schreib zwei Fragen und zwei Antworten mit „wenn".',
             'beispiel': '— Was machst du im Sommer? — Wenn ich Urlaub habe, dann fliege ich nach Italien. — Und wenn nicht? — Dann fahre ich nur am Wochenende ans Meer.'},
        ]
    },
    '1066X': {
        'lesson_code': '1066X',
        'lesson_title': 'Genus und Adjektivendungen',
        'banner_url': BANNER[0], 'banner_alt': BANNER[1],
        'intro': 'Fünf kleine Schreibaufgaben rund um Genus und Adjektivendungen.',
        'tasks': [
            {'titel': 'Ein Foto beschreiben', 'frage': 'Beschreib ein Foto oder Bild mit drei Adjektiven (mit Endungen).',
             'beispiel': 'Auf dem Foto sehe ich eine schöne Frau. Sie hat lange braune Haare. Sie trägt ein grünes Kleid.'},
            {'titel': 'Drei Lieblingssachen', 'frage': 'Beschreib drei Sachen aus deinem Zuhause mit Adjektiven.',
             'beispiel': 'Ich habe ein altes Klavier, einen großen Esstisch und einen kleinen weißen Hund.'},
            {'titel': 'Im Geschäft', 'frage': 'Stell dir vor, du kaufst Kleidung. Beschreib drei Sachen mit Adjektivendung.',
             'beispiel': 'Ich suche eine schwarze Hose. Ich brauche auch ein blaues Hemd und einen warmen Pullover.'},
            {'titel': 'Eine Person beschreiben', 'frage': 'Beschreib eine Person mit drei Adjektiven.',
             'beispiel': 'Mein bester Freund ist ein netter und freundlicher Mensch. Er hat blaue Augen und kurze braune Haare.'},
            {'titel': 'Mini-Dialog: Im Geschäft', 'frage': 'Du bist im Geschäft. Schreib zwei Fragen und zwei Antworten mit Adjektivendungen.',
             'beispiel': '— Haben Sie diese rote Bluse auch in Größe 38? — Ja, hier ist eine kleine. — Gibt es das Hemd in einer anderen Farbe? — Wir haben blaue und weiße.'},
        ]
    },
    '2012X': {
        'lesson_code': '2012X',
        'lesson_title': 'Im Feinkostladen',
        'banner_url': BANNER[0], 'banner_alt': BANNER[1],
        'intro': 'Fünf kleine Schreibaufgaben rund um Einkaufen, Ernährung und Allergien.',
        'tasks': [
            {'titel': 'Im Supermarkt', 'frage': 'Was kaufst du heute im Feinkostladen? Schreib drei Sachen mit Mengen.',
             'beispiel': 'Ich kaufe 200 Gramm Käse, eine Flasche Olivenöl und ein Pfund Bio-Tomaten.'},
            {'titel': 'Allergien und Diäten', 'frage': 'Hast du eine Allergie oder eine besondere Ernährung? Schreib zwei Sätze.',
             'beispiel': 'Ich vertrage keine Laktose. Deshalb kaufe ich nur laktosefreie Milch und keinen normalen Käse.'},
            {'titel': 'Vegetarisch oder vegan?', 'frage': 'Was hältst du von vegetarischer oder veganer Ernährung? Schreib zwei Sätze.',
             'beispiel': 'Ich finde vegetarisch gut, weil es gesund ist. Vegan ist mir zu schwierig — ich liebe Käse zu sehr.'},
            {'titel': 'Drei Tipps für gesunde Ernährung', 'frage': 'Schreib drei Tipps für gute Ernährung.',
             'beispiel': 'Ess viel Gemüse und Obst. Trink mindestens zwei Liter Wasser. Iss nicht zu viel Fast Food.'},
            {'titel': 'Mini-Dialog: Im Feinkostladen', 'frage': 'Du fragst nach einer Allergie-Lebensmittel. Schreib zwei Fragen und zwei Antworten.',
             'beispiel': '— Haben Sie glutenfreies Brot? — Ja, in der ersten Reihe. — Wie lange ist es haltbar? — Mindestens fünf Tage.'},
        ]
    },
    '2016X': {
        'lesson_code': '2016X',
        'lesson_title': 'Rezepte',
        'banner_url': BANNER[0], 'banner_alt': BANNER[1],
        'intro': 'Fünf kleine Schreibaufgaben rund um Rezepte und Kochen.',
        'tasks': [
            {'titel': 'Dein Lieblingsrezept', 'frage': 'Was kochst du gern? Welche Zutaten brauchst du? Schreib zwei oder drei Sätze.',
             'beispiel': 'Ich koche gern Spaghetti Bolognese. Ich brauche Hackfleisch, Tomaten, Zwiebeln und Knoblauch. Es schmeckt sehr gut.'},
            {'titel': 'Ein Rezept in 3 Schritten', 'frage': 'Erkläre ein einfaches Rezept in drei Schritten mit Imperativ.',
             'beispiel': 'Schneide eine Zwiebel klein. Brate sie mit Olivenöl an. Gib dann die Tomaten dazu und koche zehn Minuten.'},
            {'titel': 'Kochverben', 'frage': 'Schreib drei Sätze mit Kochverben (schneiden, braten, kochen, würzen).',
             'beispiel': 'Ich schneide das Gemüse. Dann brate ich das Fleisch. Am Ende würze ich mit Salz und Pfeffer.'},
            {'titel': 'Ein Missgeschick beim Kochen', 'frage': 'Was ist dir beim Kochen schon einmal schiefgegangen? Schreib zwei Sätze.',
             'beispiel': 'Letzte Woche habe ich die Suppe versalzen. Wir mussten am Ende etwas anderes essen.'},
            {'titel': 'Mini-Dialog: Beim Kochen', 'frage': 'Du kochst mit einem Freund. Schreib zwei Fragen und zwei Antworten.',
             'beispiel': '— Hast du die Zwiebeln schon geschnitten? — Ja, sie sind in der Pfanne. — Wie viel Salz nehmen wir? — Nur einen Teelöffel, das reicht.'},
        ]
    },
    '2022X': {
        'lesson_code': '2022X',
        'lesson_title': 'Mein letzter Urlaub',
        'banner_url': BANNER[0], 'banner_alt': BANNER[1],
        'intro': 'Fünf kleine Schreibaufgaben rund um Urlaub und Reisen mit Präpositionen.',
        'tasks': [
            {'titel': 'Dein letzter Urlaub', 'frage': 'Wo warst du im letzten Urlaub? Wie lange? Schreib zwei Sätze.',
             'beispiel': 'Im letzten Sommer war ich in Italien am Meer. Wir waren zwei Wochen dort und es war fantastisch.'},
            {'titel': 'Drei Urlaubsmomente', 'frage': 'Schreib drei Erinnerungen aus einem Urlaub.',
             'beispiel': 'Wir haben jeden Tag am Strand gelegen. Abends haben wir gut gegessen. Einmal sind wir mit dem Boot gefahren.'},
            {'titel': 'Heimweh oder Fernweh?', 'frage': 'Hast du Heimweh oder Fernweh, wenn du im Urlaub bist? Schreib zwei Sätze.',
             'beispiel': 'Im Urlaub habe ich nie Heimweh. Aber zu Hause habe ich oft Fernweh nach den Bergen oder dem Meer.'},
            {'titel': 'Eine Postkarte schreiben', 'frage': 'Schreib eine kurze Postkarte aus dem Urlaub (3-4 Sätze).',
             'beispiel': 'Liebe Anna! Wir sind seit drei Tagen in Lissabon. Die Stadt ist sehr schön. Das Wetter ist warm. Bis bald, Maria.'},
            {'titel': 'Mini-Dialog: Reisepläne', 'frage': 'Sprecht über Urlaubspläne. Schreib zwei Fragen und zwei Antworten.',
             'beispiel': '— Wohin fährst du in den Sommerferien? — Wir fahren nach Frankreich. — Wie lange? — Drei Wochen, von Juli bis August.'},
        ]
    },
    '2026X': {
        'lesson_code': '2026X',
        'lesson_title': 'Versteh mich nicht falsch',
        'banner_url': BANNER[0], 'banner_alt': BANNER[1],
        'intro': 'Fünf kleine Schreibaufgaben rund um Missverständnisse und Kommunikation.',
        'tasks': [
            {'titel': 'Ein Missverständnis', 'frage': 'Hattest du schon einmal ein Missverständnis? Was ist passiert? Schreib zwei Sätze.',
             'beispiel': 'Letzte Woche habe ich einen Kollegen falsch verstanden. Ich dachte, das Meeting ist um zehn — es war aber um neun.'},
            {'titel': 'Etwas klarstellen', 'frage': 'Schreib drei Sätze, um ein Missverständnis zu klären.',
             'beispiel': 'Entschuldigung, ich habe das anders gemeint. Lass mich das genauer erklären. Ich wollte nur sagen, dass ich müde bin.'},
            {'titel': 'Höflich nachfragen', 'frage': 'Du verstehst etwas nicht. Schreib drei höfliche Nachfragen.',
             'beispiel': 'Entschuldigung, kannst du das wiederholen? Könnten Sie das bitte langsamer sagen? Was meinst du genau damit?'},
            {'titel': 'Körpersprache', 'frage': 'Wie wichtig ist Körpersprache für dich? Schreib zwei Sätze.',
             'beispiel': 'Ich finde Körpersprache sehr wichtig. Wenn jemand lächelt, fühle ich mich wohler.'},
            {'titel': 'Mini-Dialog: Bei einem Missverständnis', 'frage': 'Schreib einen Mini-Dialog bei einem Missverständnis: zwei Fragen und zwei Antworten.',
             'beispiel': '— Du hast gesagt, du kommst um sechs! — Nein, ich habe gesagt um sieben. — Echt? Da habe ich dich falsch verstanden. — Kein Problem, jetzt ist alles klar.'},
        ]
    },
    '2032X': {
        'lesson_code': '2032X',
        'lesson_title': 'Was soll ich anziehen?',
        'banner_url': BANNER[0], 'banner_alt': BANNER[1],
        'intro': 'Fünf kleine Schreibaufgaben rund um Kleidung und Komparativ.',
        'tasks': [
            {'titel': 'Dein Lieblings-Outfit', 'frage': 'Was trägst du am liebsten? Beschreib es in zwei oder drei Sätzen.',
             'beispiel': 'Ich trage am liebsten Jeans und ein T-Shirt. Im Winter ziehe ich noch einen warmen Pullover an. Es ist bequem und praktisch.'},
            {'titel': 'Drei Vergleiche', 'frage': 'Vergleich Kleidung. Schreib drei Sätze mit Komparativ („als").',
             'beispiel': 'Mein schwarzer Anzug ist eleganter als mein grauer. Diese Bluse ist teurer als jene. Im Sommer ziehe ich kürzere Hosen an als im Winter.'},
            {'titel': 'Was ziehst du wann an?', 'frage': 'Was trägst du zur Arbeit? Was zu Hause? Schreib zwei Sätze.',
             'beispiel': 'Zur Arbeit ziehe ich ein Hemd und eine Hose an. Zu Hause trage ich lieber bequeme Sachen wie eine Jogginghose.'},
            {'titel': 'Beim Schneider', 'frage': 'Was lässt du beim Schneider machen? Schreib zwei Sätze.',
             'beispiel': 'Ich lasse mir die Hose kürzer machen. Beim Schneider lasse ich auch ein Hemd ändern, weil es zu groß ist.'},
            {'titel': 'Mini-Dialog: Im Bekleidungsgeschäft', 'frage': 'Du kaufst eine Jacke. Schreib zwei Fragen und zwei Antworten mit Komparativ.',
             'beispiel': '— Haben Sie diese Jacke in einer kleineren Größe? — Ja, hier in M. — Gibt es noch eine wärmere? — Diese hier ist dicker und wärmer als die andere.'},
        ]
    },
    '2036X': {
        'lesson_code': '2036X',
        'lesson_title': 'Beim Einwohnermeldeamt',
        'banner_url': BANNER[0], 'banner_alt': BANNER[1],
        'intro': 'Fünf kleine Schreibaufgaben rund um Behördengänge und Anmeldung.',
        'tasks': [
            {'titel': 'Anmeldung in einer neuen Stadt', 'frage': 'Was musst du machen, wenn du in eine neue Stadt ziehst? Schreib zwei Sätze.',
             'beispiel': 'Ich muss zum Einwohnermeldeamt gehen und mich anmelden. Ich brauche meinen Personalausweis und einen Mietvertrag.'},
            {'titel': 'Ein Dokument beantragen', 'frage': 'Welches Dokument hast du schon einmal beantragt? Schreib zwei Sätze.',
             'beispiel': 'Letztes Jahr habe ich einen neuen Reisepass beantragt. Ich musste ein neues Passfoto und ein Formular mitbringen.'},
            {'titel': 'Auf einem Formular', 'frage': 'Was schreibst du auf ein Anmeldeformular? Schreib drei Angaben.',
             'beispiel': 'Ich schreibe meinen Namen, meine neue Adresse und mein Geburtsdatum. Am Ende muss ich unterschreiben.'},
            {'titel': 'Eine Frage an den Beamten', 'frage': 'Schreib zwei höfliche Fragen an einen Beamten beim Einwohnermeldeamt.',
             'beispiel': 'Entschuldigung, wie lange dauert die Anmeldung? Brauche ich auch noch andere Dokumente?'},
            {'titel': 'Mini-Dialog: Im Bürgerbüro', 'frage': 'Du meldest dich an. Schreib zwei Fragen und zwei Antworten.',
             'beispiel': '— Guten Tag, ich möchte mich anmelden. — Haben Sie das Formular dabei? — Ja, hier bitte. — Auch Ausweis und Mietvertrag? — Ja, alles ist da.'},
        ]
    },
    '2042X': {
        'lesson_code': '2042X',
        'lesson_title': 'Einen Lebenslauf schreiben',
        'banner_url': BANNER[0], 'banner_alt': BANNER[1],
        'intro': 'Fünf kleine Schreibaufgaben rund um Lebenslauf und Bewerbung.',
        'tasks': [
            {'titel': 'Deine Ausbildung', 'frage': 'Welchen Schulabschluss hast du? Was hast du studiert oder gelernt? Schreib zwei oder drei Sätze.',
             'beispiel': 'Ich habe das Abitur gemacht und danach Wirtschaft studiert. Mein Studium habe ich 2018 mit dem Bachelor abgeschlossen.'},
            {'titel': 'Drei Stationen aus deinem Lebenslauf', 'frage': 'Schreib drei wichtige Stationen aus deinem beruflichen Leben.',
             'beispiel': '2018: Bachelor in Wirtschaft. 2019: Praktikum in einer Bank. 2020 bis heute: Sekretärin in einer Anwaltskanzlei.'},
            {'titel': 'Deine Qualifikationen', 'frage': 'Was kannst du gut? Schreib zwei oder drei Qualifikationen.',
             'beispiel': 'Ich spreche Englisch und Spanisch. Ich kenne mich mit Excel und Word sehr gut aus. Ich arbeite gern im Team.'},
            {'titel': 'Erste Zeile eines Anschreibens', 'frage': 'Schreib die erste Zeile (Anrede + Einleitung) für ein Anschreiben.',
             'beispiel': 'Sehr geehrte Frau Meier, ich habe Ihre Stellenanzeige in der Zeitung gelesen und möchte mich um die Stelle bewerben.'},
            {'titel': 'Mini-Dialog: Im Vorstellungsgespräch', 'frage': 'Schreib zwei Fragen und zwei Antworten aus einem Gespräch.',
             'beispiel': '— Wie viel Berufserfahrung haben Sie? — Drei Jahre als Sekretärin. — Was war Ihr letzter Abschluss? — Der Bachelor in Wirtschaft.'},
        ]
    },
    '2046X': {
        'lesson_code': '2046X',
        'lesson_title': 'Finalsätze',
        'banner_url': BANNER[0], 'banner_alt': BANNER[1],
        'intro': 'Fünf kleine Schreibaufgaben mit Finalsätzen (damit / um … zu).',
        'tasks': [
            {'titel': 'Warum lernst du Deutsch?', 'frage': 'Schreib zwei Sätze mit „damit" oder „um zu" über deinen Deutsch-Unterricht.',
             'beispiel': 'Ich lerne Deutsch, um in Deutschland zu arbeiten. Ich lerne Deutsch, damit ich besser mit deutschen Kollegen sprechen kann.'},
            {'titel': 'Drei Ziele', 'frage': 'Schreib drei Lebensziele mit „um … zu …".',
             'beispiel': 'Ich spare Geld, um ein Auto zu kaufen. Ich mache Sport, um fit zu bleiben. Ich lese viel, um schlauer zu werden.'},
            {'titel': 'Drei Sätze mit „damit"', 'frage': 'Schreib drei Sätze mit „damit" — wenn die Subjekte unterschiedlich sind.',
             'beispiel': 'Mama kocht gesund, damit wir Vitamine bekommen. Ich rufe ihn an, damit er nicht traurig ist. Wir lernen Englisch, damit unsere Eltern stolz sind.'},
            {'titel': 'Was machst du, um glücklich zu sein?', 'frage': 'Schreib zwei Sätze über dein Glück mit „um zu".',
             'beispiel': 'Ich gehe oft spazieren, um den Kopf frei zu haben. Ich treffe Freunde, um nicht einsam zu sein.'},
            {'titel': 'Mini-Dialog: Über Pläne', 'frage': 'Sprecht über Pläne mit Finalsätzen. Schreib zwei Fragen und zwei Antworten.',
             'beispiel': '— Warum machst du einen Sprachkurs? — Um in Spanien arbeiten zu können. — Und du? — Ich lerne Deutsch, damit meine Familie stolz auf mich ist.'},
        ]
    },
    '2052X': {
        'lesson_code': '2052X',
        'lesson_title': 'Eine E-Mail schreiben',
        'banner_url': BANNER[0], 'banner_alt': BANNER[1],
        'intro': 'Fünf kleine Schreibaufgaben rund um formelle und informelle E-Mails.',
        'tasks': [
            {'titel': 'Eine formelle Anrede', 'frage': 'Schreib drei formelle Anreden für E-Mails.',
             'beispiel': 'Sehr geehrte Frau Müller, sehr geehrter Herr Wagner, sehr geehrte Damen und Herren.'},
            {'titel': 'Eine kurze formelle E-Mail', 'frage': 'Schreib eine kurze E-Mail an einen Kunden (4-5 Sätze).',
             'beispiel': 'Sehr geehrter Herr Müller, vielen Dank für Ihre Anfrage. Den Termin am Montag kann ich leider nicht. Wäre Dienstag um 10 Uhr möglich? Mit freundlichen Grüßen, Maria Lopez.'},
            {'titel': 'Eine kurze informelle E-Mail', 'frage': 'Schreib eine kurze Nachricht an einen Freund (4-5 Sätze).',
             'beispiel': 'Lieber Tom, wie geht es dir? Hast du am Samstag Zeit? Lass uns ins Kino gehen. Liebe Grüße, deine Maria.'},
            {'titel': 'Drei Grußformeln', 'frage': 'Schreib drei verschiedene Grußformeln (formell und informell).',
             'beispiel': 'Mit freundlichen Grüßen — formell. Liebe Grüße — semi-formell. Bis bald, dein Tom — sehr informell.'},
            {'titel': 'Mini-Dialog: Termin per E-Mail', 'frage': 'Du verschiebst einen Termin per E-Mail. Schreib zwei Sätze und die Antwort (zwei Sätze).',
             'beispiel': '— Sehr geehrte Frau Müller, leider kann ich am Donnerstag nicht. Wäre Freitag möglich? — Sehr geehrter Herr Schmidt, Freitag um 10 Uhr passt mir gut. Bis dann!'},
        ]
    },
    '2056X': {
        'lesson_code': '2056X',
        'lesson_title': 'Auf dem Laufenden bleiben',
        'banner_url': BANNER[0], 'banner_alt': BANNER[1],
        'intro': 'Fünf kleine Schreibaufgaben rund um Diskussion, Meinung und gesellschaftliche Themen.',
        'tasks': [
            {'titel': 'Deine Meinung zu Nachrichten', 'frage': 'Wie informierst du dich? Schreib zwei Sätze.',
             'beispiel': 'Ich lese morgens die Zeitung am Handy. Abends schaue ich manchmal Nachrichten im Fernsehen.'},
            {'titel': 'Ein gesellschaftliches Thema', 'frage': 'Welches Thema findest du wichtig — z.B. Armut, Mieten, Bildung? Schreib zwei Sätze.',
             'beispiel': 'Ich finde steigende Mieten ein großes Problem. Junge Familien können sich oft keine Wohnung mehr leisten.'},
            {'titel': 'Diskussionsregeln', 'frage': 'Schreib drei Regeln für eine gute Diskussion.',
             'beispiel': 'Lass die andere Person ausreden. Unterbrich nicht ständig. Bleib höflich, auch bei anderer Meinung.'},
            {'titel': 'Pro und contra', 'frage': 'Schreib einen Pro- und einen Contra-Satz zu einem Thema deiner Wahl.',
             'beispiel': 'Pro Home-Office: Ich kann produktiver arbeiten. Contra Home-Office: Ich vermisse den Kontakt mit Kollegen.'},
            {'titel': 'Mini-Dialog: Eine Diskussion', 'frage': 'Diskutiert über Social Media. Schreib zwei Fragen und zwei Antworten.',
             'beispiel': '— Findest du Social Media positiv? — Ich denke, dass es Vor- und Nachteile gibt. — Welche Nachteile? — Man verbringt zu viel Zeit am Handy.'},
        ]
    },
    '2062X': {
        'lesson_code': '2062X',
        'lesson_title': 'Häufige Präfixe von Verben',
        'banner_url': BANNER[0], 'banner_alt': BANNER[1],
        'intro': 'Fünf kleine Schreibaufgaben mit trennbaren und nicht trennbaren Verben.',
        'tasks': [
            {'titel': 'Drei trennbare Verben', 'frage': 'Schreib drei Sätze mit trennbaren Verben (anrufen, mitkommen, aufstehen).',
             'beispiel': 'Ich rufe meine Mutter jeden Sonntag an. Kommst du heute Abend mit? Morgen stehe ich um sechs Uhr auf.'},
            {'titel': 'Drei nicht trennbare Verben', 'frage': 'Schreib drei Sätze mit nicht trennbaren Verben (bestellen, verstehen, erklären).',
             'beispiel': 'Ich bestelle eine Pizza. Verstehst du die Aufgabe? Mein Lehrer erklärt das immer gut.'},
            {'titel': 'Verben im Perfekt', 'frage': 'Schreib zwei Sätze im Perfekt — einen mit trennbarem, einen mit nicht trennbarem Verb.',
             'beispiel': 'Gestern bin ich um sieben aufgestanden. Letzte Woche habe ich eine neue Wohnung gefunden.'},
            {'titel': 'Eine Bitte mit „bitte"', 'frage': 'Schreib drei Bitten mit trennbaren Verben.',
             'beispiel': 'Mach bitte das Fenster auf! Ruf mich später an! Bring bitte das Brot mit!'},
            {'titel': 'Mini-Dialog: Pläne machen', 'frage': 'Schreib zwei Fragen und zwei Antworten mit verschiedenen Präfix-Verben.',
             'beispiel': '— Kommst du morgen mit ins Kino? — Ja, gern. Wann fängt der Film an? — Um neun Uhr. — Okay, ich rufe dich nachmittags an.'},
        ]
    },
    '2066X': {
        'lesson_code': '2066X',
        'lesson_title': 'Lokale und Wechselpräpositionen',
        'banner_url': BANNER[0], 'banner_alt': BANNER[1],
        'intro': 'Fünf kleine Schreibaufgaben mit lokalen Präpositionen (durch, um, gegen, aus, zu, nach).',
        'tasks': [
            {'titel': 'Ein Spaziergang', 'frage': 'Beschreib einen Spaziergang mit drei Präpositionen (durch, um, entlang).',
             'beispiel': 'Ich gehe durch den Park. Dann laufe ich um den See herum. Am Ende gehe ich die Straße entlang nach Hause.'},
            {'titel': 'Wo bist du?', 'frage': 'Wo bist du an drei verschiedenen Orten? Schreib drei Sätze mit Dativ-Präpositionen.',
             'beispiel': 'Morgens bin ich bei meiner Familie. Mittags bin ich aus dem Büro. Abends fahre ich zu Freunden.'},
            {'titel': 'Drei Reiseziele', 'frage': 'Wohin möchtest du reisen? Schreib drei Sätze mit „nach", „in" oder „zu".',
             'beispiel': 'Im Sommer fahre ich nach Italien. Nächstes Jahr möchte ich in die USA fliegen. Im Winter fahre ich zu meiner Oma.'},
            {'titel': 'Innerhalb oder außerhalb?', 'frage': 'Schreib zwei Sätze mit „innerhalb" oder „außerhalb".',
             'beispiel': 'Mein Büro liegt innerhalb der Stadt, in der Innenstadt. Mein Haus ist außerhalb des Zentrums, in einem ruhigen Viertel.'},
            {'titel': 'Mini-Dialog: Nach dem Weg fragen', 'frage': 'Frag und antworte mit Präpositionen.',
             'beispiel': '— Wie komme ich zum Bahnhof? — Geh durch die Fußgängerzone bis zur Kirche. — Und dann? — Dann links entlang der Straße. Nach 200 Metern bist du da.'},
        ]
    },
}
